export const data = [
  {
    id: 1,
    name: 'Cultus Efi',
    image: '/images/product/suzuki/airfilter/cultus-efi.jpg',
    car: 'Suzuki',
    type: 'Air Filter',
    brand: 'Leppon',
    sale: true,
    model: 'Cultus Efi',
    price: 900,
    sprice: 800,
    qty: 20,
    rating: 4.5,
    numReviews: 10,
    tsale: 0,
    stock: 20,
    description: 'Suzuki Cultus Efi Air Filter',
  },
  {
    id: 2,
    name: 'Cultus Old',
    image: '/images/product/suzuki/airfilter/cultus-old.jpg',
    car: 'Suzuki',
    type: 'Air Filter',
    brand: 'Leppon',
    model: 'Cultus Old',
    price: 900,
    qty: 20,
    rating: 3.5,
    numReviews: 10,
    tsale: 0,
    stock: 20,
    description: 'Suzuki Cultus Old Air Filter',
  },
  {
    id: 3,
    name: 'Alto 2019',
    image: '/images/product/suzuki/airfilter/alto660new.jpg',
    car: 'Suzuki',
    type: 'Air Filter',
    brand: 'Leppon',
    model: 'Alto 2019 660cc',
    price: 900,
    qty: 20,
    rating: 4.5,
    numReviews: 10,
    tsale: 0,
    stock: 20,
    description: 'Suzuki Alto 2019 660cc Air Filter',
  },
  {
    id: 4,
    name: 'Suzuki Chamber',
    image: '/images/product/suzuki/airfilter/chamber.jpg',
    car: 'Suzuki',
    type: 'Air Filter',
    brand: 'Leppon',
    model: 'Suzuki Chamber',
    price: 900,
    qty: 20,
    rating: 4.5,
    numReviews: 10,
    tsale: 0,
    stock: 20,
    description: 'Suzuki Chamber Air Filter',
  },
  {
    id: 5,
    name: 'Suzuki Chamber',
    image: '/images/product/suzuki/airfilter/chamber.jpg',
    car: 'Suzuki',
    type: 'Air Filter',
    brand: 'Leppon',
    model: 'Suzuki Chamber',
    price: 900,
    qty: 20,
    rating: 4.5,
    numReviews: 10,
    tsale: 0,
    stock: 20,
    description: 'Suzuki Chamber Air Filter',
  },
]
